# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Prepare release
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  prepare:
    name: Prepare release pull request
    if: github.event.label.name == 'release:prepare'
    uses: connectbot/release-action/.github/workflows/prepare-release.yml@851920620b16b907783a16c7f93d984bbda1d2eb # main
    with:
      tag_prefix: "v"
      gradle_no_push_prop: cbssh.release.noPush
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
