# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create release branch
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  branch:
    name: Create maintenance branch
    if: github.event.label.name == 'release:branch'
    uses: connectbot/release-action/.github/workflows/release-branch.yml@851920620b16b907783a16c7f93d984bbda1d2eb # main
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
