# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish release
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  publish:
    name: Publish release tag and branch
    if: github.event.label.name == 'release:publish'
    uses: connectbot/release-action/.github/workflows/publish-release.yml@851920620b16b907783a16c7f93d984bbda1d2eb # main
    with:
      tag_prefix: "v"
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
